### ISSUE TITLE
Errors Spamming Console

### ISSUE THREAD

**Issue by nullschritt** [sofar/Sedimentology#1] opened 2014-01-13 05:59 UTC
I get the following errors, spamming my console, and resulting in a server crash. This just started occuring today.

[Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException: 0
    at org.foo_projects.sofar.Sedimentology.Sedimentology$SedWorld.sedRandomBlock(Sedimentology.java:369) ~[?:?]
    at org.foo_projects.sofar.Sedimentology.Sedimentology$SedimentologyRunnable.run(Sedimentology.java:996) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[craftbukkit.jar:git-Spigot-1204]
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:583) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:259) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:540) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:446) [craftbukkit.jar:git-Spigot-1204]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Spigot-1204]
[23:05:15] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:15] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:15] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:15] [pool-6-thread-1/INFO]: GroupManager - INFO -  Data files refreshed.
[23:05:17] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:25] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:25] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:25] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:31] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:31] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:31] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:45] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:45] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:46] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:46] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:47] [Craft Scheduler Thread - 62/INFO]: [MineBackup]  \* saving worlds\main_the_end
[23:05:47] [Server thread/WARN]: A manual (plugin-induced) save has been detected while server is configured to auto-save. This may affect performance.
[23:05:49] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:50] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:05:50] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:02] [Craft Scheduler Thread - 62/INFO]: [0;33;1mTo protect the welfare of our citizens, all tnt damage more than 40 blocks up will be automatically reversed. You can still use tnt to mine, just make sure youre less than 40 blocks high!(press F3)[m
[23:06:12] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:12] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:12] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:12] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:14] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:14] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:14] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:16] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:16] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:16] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:17] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:39] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:39] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:39] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:06:49] [Craft Scheduler Thread - 11/INFO]: [MineBackup]  \* copying worlds\main_the_end
[23:06:55] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:01] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:11] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:12] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:12] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:12] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:20] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:40] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:40] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:40] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:50] [Craft Scheduler Thread - 62/INFO]: [MineBackup]  - TaskProcess already working - it's already been a minute?!
[23:07:56] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:57] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:07:57] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:01] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:01] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:01] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:05] [Craft Scheduler Thread - 8/INFO]: [0;33;1mTIP: Place gold or diamond blocks under a track to boost the cart speed![m
[23:08:07] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:07] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:07] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:07] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:33] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:33] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:33] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:34] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:52] [Craft Scheduler Thread - 65/INFO]: [MineBackup]  - TaskProcess already working - it's already been a minute?!
[23:08:52] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:52] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:52] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:58] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:58] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:58] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:08:58] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:09:22] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:09:22] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:09:23] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:09:23] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:09:29] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:09:29] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:09:29] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:09:53] [Craft Scheduler Thread - 65/INFO]: [MineBackup]  - TaskProcess already working - it's already been a minute?!
[23:10:08] [Craft Scheduler Thread - 62/INFO]: [0;33;1mYou can sell your land with signs! On the first line type [ForSale]. On the second line type the price. On the third line type an optional property name.[m
[23:10:24] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:10:55] [Craft Scheduler Thread - 66/INFO]: [MineBackup]  - TaskProcess already working - it's already been a minute?!
[23:10:55] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:11:44] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:11:44] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:11:44] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:11:45] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:11:57] [Craft Scheduler Thread - 66/INFO]: [MineBackup]  \* copying worlds\TARDIS_TimeVortex
[23:12:11] [Craft Scheduler Thread - 62/INFO]: [0;33;1mTIP:You can view a list of all stargates by using "/gate list", and then see its address with "/gate info"! For help on using gates, see the gatekeeper at the spawn.[m
[23:12:21] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:12:42] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:12:42] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:12:42] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:12:58] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:12:58] [Craft Scheduler Thread - 62/INFO]: [MineBackup]  \* copying others\plugins
[23:13:04] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:13:17] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:14:00] [Craft Scheduler Thread - 66/INFO]: [MineBackup]  \* saving worlds\main
[23:14:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:14:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:14:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:14:14] [Craft Scheduler Thread - 66/INFO]: [0;33;1mTIP: Everyone starts out with 5 hearts. To earn more simply start killing mobs. To see your hp info type /hp.[m
[23:14:18] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:14:31] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:15:01] [Craft Scheduler Thread - 66/INFO]: [MineBackup]  \* copying worlds\main
[23:15:44] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:16:03] [Craft Scheduler Thread - 77/INFO]: [MineBackup]  - TaskProcess already working - it's already been a minute?!
[23:16:17] [Craft Scheduler Thread - 84/INFO]: [0;33;1mTIP: When building near water, use non-erodable blocks, or part of your building might get washed away![m
[23:16:34] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:16:46] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:16:52] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:17:04] [Craft Scheduler Thread - 84/INFO]: [MineBackup]  - TaskProcess already working - it's already been a minute?!
[23:17:54] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:18:06] [Craft Scheduler Thread - 88/INFO]: [MineBackup]  - TaskProcess already working - it's already been a minute?!
[23:18:22] [Craft Scheduler Thread - 84/INFO]: [0;33;1mDid you know that you can build you own stargate for fast travel? To see how visit http://projectbuilder.info/?page=faq and search "stargate".[m
[23:18:38] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:18:50] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:18:56] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:18:56] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:18:57] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:18:57] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:19:09] [Craft Scheduler Thread - 88/INFO]: [MineBackup]  \* saving worlds\SkyLands
[23:19:58] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:20:10] [Craft Scheduler Thread - 84/INFO]: [MineBackup]  \* copying worlds\SkyLands
[23:20:24] [Craft Scheduler Thread - 89/INFO]: [0;33;1mTo quickly whisper to somebody simply type "@username message"(you can abbreviate names). To reply to the last received message just type "/r message".[m
[23:20:27] [Server thread/INFO]: _=_=_=_=_=_=_=_= LagFixer =_=_=_=_=_=_=_=_
[23:20:27] [Server thread/INFO]: Current Memory (Free/Max | Used (%)): 274MB/365MB | 91MB (24%)
[23:20:29] [Server thread/INFO]: Tasks Done! Time needed: 1527 milliseconds! (= 1 sec)
[23:20:29] [Server thread/INFO]: Current Memory (Free/Max | Used (%)): 854MB/365MB | -489MB (-133%)
[23:20:29] [Server thread/INFO]: _=_=_=_=_=_=_=_= LagFixer =_=_=_=_=_=_=_=_
[23:21:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:00] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:18] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:36] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:36] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:37] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:37] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:43] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:49] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:55] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:55] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:55] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:21:55] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:22:01] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:22:28] [Craft Scheduler Thread - 84/INFO]: [0;33;1mBeware of vampires, fighting with them may cause you to contract the dark disease.[m
[23:22:40] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:22:40] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:22:40] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:22:44] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:23:21] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:23:27] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:23:59] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:24:32] [Craft Scheduler Thread - 88/INFO]: [0;33;1mTIP: When building near water, use non-erodable blocks, or part of your building might get washed away![m
[23:24:36] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:24:42] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:24:42] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:24:42] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:24:43] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:24:56] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:25:08] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:25:08] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:25:09] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception
java.lang.ArrayIndexOutOfBoundsException
[23:25:09] [Server thread/WARN]: [Sedimentology] Task #1434 for Sedimentology v8 generated an exception

**Comment by nullschritt** [comment] 2014-01-13 06:07
Spigot-1.7.2.R02 (Bukkit R02 API)
Sedimentology-8

**Comment by nullschritt** [comment] 2014-01-13 08:37
Sedementoloy-9 doesn't seem to produce these errors as of yet.

**Comment by sofar** [comment] 2014-01-13 15:49
So this and the other bug point to a bug I found earlier where getLoadedChunks() returns 0, and it would subsequently attempt to use the empty array - hence the java exception here.

This may happen if you have sedimentology enabled but nobody logged in in a world at all, and your server is configured to _unload_ the entire spawn area, so 0 blocks are loaded.

I'll try and scan the code for other places I need to check for this condition.

**Comment by sofar** [comment] 2014-01-13 17:30
Fixed by:

https://github.com/sofar/Sedimentology/commit/52cf47714ccbdc561ff2db5a80f1c68b7caa9053

**Comment by sofar** [comment] 2014-01-13 17:30
Since this is confirmed fixed in v9 I'm closing this issue. The other issue still needs a check so that won't be until v10.

**Closed as completed by sofar** 2014-01-13 17:30 UTC
Labels: bug
